export const navGroups = [
  {
    id: 'employee-services',
    label: 'Pitstop',
    description: 'HR, payroll & personal services',
    icon: 'User',
    colorKey: 'blue',
    collapsible: true,
    items: [
      { id: 'team-directory', label: 'Team Directory', icon: 'Users', sectionId: 'self-service' },
      { id: 'policies', label: 'Policies', icon: 'ClipboardCheck', sectionId: 'self-service' },
      { id: 'travel', label: 'Travel', icon: 'Plane', sectionId: 'self-service' },
      {
        id: 'recognition-gem',
        label: 'Recognition - GEM',
        icon: 'Award',
        sectionId: 'self-service',
      },
      {
        id: 'compensation',
        label: 'Compensation',
        icon: 'IndianRupee',
        sectionId: 'self-service',
      },
      {
        id: 'leave-attendance',
        label: 'Leave / Attendance',
        icon: 'CalendarCheck',
        sectionId: 'self-service',
      },
      { id: 'benefits', label: 'Benefits', icon: 'Gift', sectionId: 'self-service' },
      {
        id: 'bolt-learning',
        label: 'BOLT - Start Learning',
        icon: 'GraduationCap',
        sectionId: 'self-service',
      },
      {
        id: 'health-wellness',
        label: 'Health & Wellness',
        icon: 'HeartPulse',
        sectionId: 'self-service',
      },
      { id: 'documents', label: 'Documents', icon: 'FolderOpen', sectionId: 'self-service' },
      { id: 'idea-hub', label: 'Idea Hub', icon: 'Lightbulb', sectionId: 'self-service' },
      {
        id: 'holiday-calendar',
        label: 'Holiday Calendar',
        icon: 'CalendarDays',
        sectionId: 'self-service',
      },
      { id: 'mediclaim', label: 'Mediclaim Card', icon: 'Shield', sectionId: 'self-service' },
      { id: 'form-16', label: 'Forms', icon: 'FileText', sectionId: 'self-service' },
      { id: 'it-summit', label: 'IT Summit', icon: 'MonitorSmartphone', sectionId: 'self-service' },
    ],
  },
  {
    id: 'it-resources-group',
    label: 'Resources & Support',
    description: 'IT, telecom & asset help',
    icon: 'Wrench',
    colorKey: 'teal',
    hideChildren: true,
    items: [
      {
        id: 'telecom-contacts',
        label: 'Resources and Support Services',
        icon: 'Phone',
        sectionId: 'it-resources',
      },
    ],
  },
  {
    id: 'locations-group',
    label: 'Bajaj Auto Presence',
    description: 'Locations & EV map',
    icon: 'MapPinned',
    colorKey: 'violet',
    hideChildren: true,
    items: [
      { id: 'locations', label: 'Bajaj Auto Presence', icon: 'Map', sectionId: 'locations' },
    ],
  },
  {
    id: 'company-news-group',
    label: 'Company News',
    description: 'Announcements & updates',
    icon: 'Newspaper',
    colorKey: 'violet',
    hideChildren: true,
    items: [
      {
        id: 'company-news',
        label: 'Company News',
        icon: 'Newspaper',
        sectionId: 'company-news',
      },
    ],
  },
  {
    id: 'bajaj-bytes-group',
    label: 'Bajaj Bytes',
    description: 'Newsletters, podcasts & videos',
    icon: 'BookOpen',
    colorKey: 'violet',
    hideChildren: true,
    items: [
      {
        id: 'bajaj-bytes',
        label: 'Bajaj Bytes',
        icon: 'BookOpen',
        sectionId: 'bajaj-bytes',
      },
    ],
  },
  {
    id: 'company-overview-group',
    label: 'Company Overview',
    description: 'Group structure & businesses',
    icon: 'Building2',
    colorKey: 'violet',
    hideChildren: true,
    items: [
      {
        id: 'company-overview',
        label: 'Company Overview',
        icon: 'Building2',
        sectionId: 'company-overview',
      },
    ],
  },
  {
    id: 'community-csr',
    label: 'Community & CSR',
    description: 'Foundation, programmes & volunteering',
    icon: 'CsrIcon',
    imageIcon: 'csrSvg',
    colorKey: 'emerald',
    hideChildren: true,
    items: [
      {
        id: 'csr',
        label: 'Community & CSR',
        icon: 'HeartHandshake',
        sectionId: 'csr',
      },
    ],
  },
  {
    id: 'emergency',
    label: 'Emergency Contacts',
    description: 'Critical & safety numbers',
    icon: 'Siren',
    colorKey: 'rose',
    hideChildren: true,
    items: [
      {
        id: 'emergency-contacts',
        label: 'Emergency Contacts',
        icon: 'PhoneCall',
        sectionId: 'emergency-contacts',
      },
    ],
  },
  {
    id: 'support-engagement',
    label: 'Support & Engagement',
    description: 'Feedback, requests & FAQs',
    icon: 'HeartHandshake',
    colorKey: 'emerald',
    hideChildren: true,
    items: [
      {
        id: 'feedback',
        label: 'Feedback / Raise Request',
        icon: 'MessageSquare',
        sectionId: 'feedback',
      },
      { id: 'help-faqs', label: 'Help / FAQs', icon: 'HelpCircle', sectionId: 'feedback' },
    ],
  },
]
