export const services = [
  {
    id: 'team-directory',
    label: 'Team Directory',
    icon: 'Users',
    redirectUrl: '#',
    enabled: true,
  },
  {
    id: 'policies',
    label: 'Policies',
    icon: 'FileText',
    redirectUrl: '#',
    enabled: true,
  },
  {
    id: 'benefits',
    label: 'Benefits',
    icon: 'Gift',
    redirectUrl: '#',
    enabled: true,
  },
  {
    id: 'travel',
    label: 'Travel',
    icon: 'Plane',
    redirectUrl: '#',
    enabled: true,
  },
  {
    id: 'leave-attendance',
    label: 'Leave / Attendance',
    icon: 'Calendar',
    redirectUrl: '#',
    enabled: true,
  },
  {
    id: 'compensation',
    label: 'Compensation',
    icon: 'IndianRupee',
    redirectUrl: '#',
    enabled: true,
  },
  {
    id: 'recognition-gem',
    label: 'Recognition – GEM',
    icon: 'Award',
    redirectUrl: '#',
    enabled: true,
  },
  {
    id: 'bolt-learning',
    label: 'BOLT – Start Learning',
    icon: 'GraduationCap',
    redirectUrl: '#',
    enabled: true,
  },
  {
    id: 'health-wellness',
    label: 'Health & Wellness',
    icon: 'Heart',
    redirectUrl: '#',
    enabled: true,
  },
  {
    id: 'holiday-calendar',
    label: 'Holiday Calendar',
    icon: 'CalendarDays',
    redirectUrl: '#',
    enabled: true,
  },
  {
    id: 'documents',
    label: 'Documents',
    icon: 'FolderOpen',
    redirectUrl: '#',
    enabled: true,
  },
  {
    id: 'idea-hub',
    label: 'Idea Hub',
    icon: 'Lightbulb',
    redirectUrl: '#',
    enabled: true,
  },
  {
    id: 'actions-pending',
    label: 'Actions Pending',
    icon: 'ClipboardCheck',
    redirectUrl: '#',
    enabled: true,
  },
]
