export const services = [
  {
    id: 'team-directory',
    label: 'Team Directory',
    icon: 'TeamDirectoryIcon',
    redirectUrl: '#',
    enabled: true,
  },
  {
    id: 'policies',
    label: 'Policies',
    icon: 'PoliciesIcon',
    redirectUrl: '#',
    enabled: true,
  },
  {
    id: 'benefits',
    label: 'Benefits',
    icon: 'BenefitsIcon',
    redirectUrl: '#',
    enabled: true,
  },
  {
    id: 'travel',
    label: 'Travel',
    icon: 'TravelIcon',
    redirectUrl: '#',
    enabled: true,
  },
  {
    id: 'leave-attendance',
    label: 'Leave / Attendance',
    icon: 'LeaveAttendanceIcon',
    redirectUrl: '#',
    enabled: true,
  },
  {
    id: 'compensation',
    label: 'Compensation',
    icon: 'CompensationIcon',
    redirectUrl: '#',
    enabled: true,
  },
  {
    id: 'recognition-gem',
    label: 'Recognition – GEM',
    icon: 'RecognitionGemIcon',
    redirectUrl: '#',
    enabled: true,
  },
  {
    id: 'bolt-learning',
    label: 'BOLT – Start Learning',
    icon: 'BoltLearningIcon',
    redirectUrl: '#',
    enabled: true,
  },
  {
    id: 'health-wellness',
    label: 'Health & Wellness',
    icon: 'HealthWellnessIcon',
    redirectUrl: '#',
    enabled: true,
  },
  {
    id: 'holiday-calendar',
    label: 'Holiday Calendar',
    icon: 'HolidayCalendarIcon',
    redirectUrl: '#',
    enabled: true,
  },
  {
    id: 'documents',
    label: 'Documents',
    icon: 'DocumentsIcon',
    redirectUrl: '#',
    enabled: true,
  },
  {
    id: 'idea-hub',
    label: 'Idea Hub',
    icon: 'IdeaHubIcon',
    redirectUrl: '#',
    enabled: true,
  },
  {
    id: 'actions-pending',
    label: 'Actions Pending',
    icon: 'ActionsPendingIcon',
    redirectUrl: '#',
    enabled: true,
  },
]
